[package]
name = "web"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "web"
path = "src/main.rs"

[dependencies]
app_core = { path = "../app_core" }
axum = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
sea-query = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tower-http = { workspace = true }
tower-sessions = { workspace = true }
tower-sessions-sqlx-store = { workspace = true }
time = { workspace = true }
reqwest = { workspace = true }
hypertext = { workspace = true }
uuid = { workspace = true }
infer = { workspace = true }
anyhow = { workspace = true }


argon2 = { version = "0.5.3", features = ["std"] }
